// app/_data/Themes.jsx
export const themes = [
  // --- Utility themes ---
  {
    key: "light",
    name: "Light",
    pageBackground: "#ffffff",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#ffffff",
    text: "#0f172a",
    primary: "#1995AD",
    border: "#e6eaf0",
    buttonText: "#ffffff",
  },
  {
    key: "dark",
    name: "Dark",
    pageBackground: "#071024",
    panelBackground: "#0b1220",
    cardBackground: "#0b1220",
    inputBackground: "#0b1220",
    text: "#e6eef8",
    primary: "#0ea5a4",
    border: "#153240",
    buttonText: "#0b1220",
  },
  {
    key: "ocean",
    name: "Ocean Blue",
    pageBackground: "#f5fbfd",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#f8fcff",
    text: "#0f172a",
    primary: "#1995AD",
    border: "#dff2fa",
    buttonText: "#ffffff",
  },
  {
    key: "sunset",
    name: "Sunset",
    pageBackground: "#fff8f3",
    panelBackground: "#fff",
    cardBackground: "#fff",
    inputBackground: "#fff7f2",
    text: "#2b2b2b",
    primary: "#ff7043",
    border: "#ffe9df",
    buttonText: "#ffffff",
  },
  {
    key: "system",
    name: "System (prefers-color-scheme)",
    pageBackground: "#ffffff",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#ffffff",
    text: "#0f172a",
    primary: "#1995AD",
    border: "#e6eaf0",
    buttonText: "#ffffff",
  },

  // --- Coding / Editor themed palettes ---
  {
    key: "monokai",
    name: "Monokai (Code)",
    pageBackground: "#272822",
    panelBackground: "#2b2b2b",
    cardBackground: "#2b2b2b",
    inputBackground: "#3a3a3a",
    text: "#f8f8f2",
    primary: "#f92672",
    border: "#3d3d3d",
    buttonText: "#ffffff",
  },
  {
    key: "github",
    name: "GitHub Light",
    pageBackground: "#f6f8fa",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#ffffff",
    text: "#24292f",
    primary: "#0366d6",
    border: "#e1e4e8",
    buttonText: "#ffffff",
  },
  {
    key: "vscode",
    name: "VS Code (Dark)",
    pageBackground: "#1e1e1e",
    panelBackground: "#252526",
    cardBackground: "#2a2d2e",
    inputBackground: "#2a2d2e",
    text: "#d4d4d4",
    primary: "#007acc",
    border: "#333438",
    buttonText: "#ffffff",
  },
  {
    key: "neon",
    name: "Neon Hacker",
    pageBackground: "#0b0f1a",
    panelBackground: "#071021",
    cardBackground: "#071021",
    inputBackground: "#081023",
    text: "#e6fff7",
    primary: "#00ffb3",
    border: "#03202a",
    buttonText: "#001217",
  },
  {
    key: "retro-code",
    name: "Retro Terminal",
    pageBackground: "#0b0c0b",
    panelBackground: "#0b0c0b",
    cardBackground: "#0d0f0d",
    inputBackground: "#0d0f0d",
    text: "#a8ff60",
    primary: "#ffb86b",
    border: "#111312",
    buttonText: "#0b0c0b",
  },

  // --- Sports themed palettes ---
  {
    key: "sports-football",
    name: "Football Pitch",
    pageBackground: "#f4faf4",
    panelBackground: "#f8fff8",
    cardBackground: "#ffffff",
    inputBackground: "#fbfff9",
    text: "#0b2a10",
    primary: "#2e8b57",
    border: "#e6efe6",
    buttonText: "#ffffff",
  },
  {
    key: "sports-basketball",
    name: "Basketball",
    pageBackground: "#fff7f0",
    panelBackground: "#fffaf6",
    cardBackground: "#fff",
    inputBackground: "#fff8f1",
    text: "#2f1a00",
    primary: "#f26522",
    border: "#ffefe3",
    buttonText: "#ffffff",
  },
  {
    key: "sports-cricket",
    name: "Cricket Pavilion",
    pageBackground: "#fbfeff",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#fbfeff",
    text: "#102a16",
    primary: "#1b8a3e",
    border: "#e9f4ea",
    buttonText: "#ffffff",
  },

  // --- Cultural themed palettes ---
  {
    key: "cultural-india",
    name: "Cultural — India",
    pageBackground: "#fffaf4",
    panelBackground: "#fff6f0",
    cardBackground: "#ffffff",
    inputBackground: "#fff8f3",
    text: "#2c1b10",
    primary: "#ff6f00",
    border: "#ffeddc",
    buttonText: "#ffffff",
  },
  {
    key: "cultural-japan",
    name: "Cultural — Japan",
    pageBackground: "#fbfbfc",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#fffdfd",
    text: "#1f2d2d",
    primary: "#e60012",
    border: "#f4e8e9",
    buttonText: "#ffffff",
  },
  {
    key: "cultural-africa",
    name: "Cultural — Africa",
    pageBackground: "#fffaf6",
    panelBackground: "#fff6f0",
    cardBackground: "#fff",
    inputBackground: "#fff8f1",
    text: "#2b160f",
    primary: "#b23b1b",
    border: "#f6e9e4",
    buttonText: "#ffffff",
  },

  // --- Misc / mood palettes ---
  {
    key: "minimal",
    name: "Minimal",
    pageBackground: "#fbfbfb",
    panelBackground: "#ffffff",
    cardBackground: "#ffffff",
    inputBackground: "#ffffff",
    text: "#111827",
    primary: "#111827",
    border: "#e6e6e6",
    buttonText: "#ffffff",
  },
  {
    key: "synthwave",
    name: "Synthwave",
    pageBackground: "#0f0430",
    panelBackground: "#160737",
    cardBackground: "#1b063f",
    inputBackground: "#180630",
    text: "#ffe9ff",
    primary: "#ff3ca6",
    border: "#2b083a",
    buttonText: "#1b063f",
  },
  {
    key: "retro-gaming",
    name: "Retro Gaming",
    pageBackground: "#0b1220",
    panelBackground: "#0f1b2b",
    cardBackground: "#112033",
    inputBackground: "#0f1b2b",
    text: "#e6f7ff",
    primary: "#f5d049",
    border: "#142235",
    buttonText: "#0f1b2b",
  },
  {
    key: "nature-forest",
    name: "Nature — Forest",
    pageBackground: "#f6fbf6",
    panelBackground: "#f9fdf9",
    cardBackground: "#ffffff",
    inputBackground: "#fbfefb",
    text: "#0f2b16",
    primary: "#166534",
    border: "#e7f3ea",
    buttonText: "#ffffff",
  },
  {
    key: "pastel",
    name: "Pastel",
    pageBackground: "#fffafc",
    panelBackground: "#fffafe",
    cardBackground: "#ffffff",
    inputBackground: "#fffdfb",
    text: "#333333",
    primary: "#a78bfa",
    border: "#f3eefc",
    buttonText: "#ffffff",
  },
  {
    key: "high-contrast",
    name: "High Contrast",
    pageBackground: "#000000",
    panelBackground: "#000000",
    cardBackground: "#000000",
    inputBackground: "#0a0a0a",
    text: "#ffffff",
    primary: "#ffff00",
    border: "#ffffff",
    buttonText: "#000000",
  },
];
